name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build API Gateway
      run: |
        cd api-gateway
        go mod download
        go build -v ./...

    - name: Build Cache Service
      run: |
        cd cache-service
        cargo build --verbose

    - name: Run API Gateway Tests
      run: |
        cd api-gateway
        go test -v ./...

    - name: Run Cache Service Tests
      run: |
        cd cache-service
        cargo test --verbose

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker Images
      run: |
        docker-compose build

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4

    - name: Run Go Security Scanner
      uses: golang/govulncheck-action@v1
      with:
        go-version: '1.21'

    - name: Run Rust Security Scanner
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 